### PR TITLE
Workaround for GHC-8.4 to provide Semigroup instance for listlike types

### PR DESCRIPTION
**Pull request by konn**
As of GHC 8.4, `Semigroup` becomes a superclass of `Monoid`.
This pull requests provides missing `Semigroup` instances for `CharString`, `Chars` and so on, so that it compiles with >= GHC-8.4.
As a side-effect, it requires `semigroups` package for GHC <8.4.

### CODE REVIEW

**Comment by asr** [comment]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got various errors on list-like.

This PR fix those errors.

Blocking https://github.com/agda/agda/issues/2878.

**Comment by asr** [comment]
@konn, I'm getting the following error using his PR on GHC 8.4.1-alpha1:

```
$ cabal install --enable-tests
...
Building test suite 'listlike-tests' for ListLike-4.5.1..
[1 of 2] Compiling TestInfrastructure ( testsrc/TestInfrastructure.hs, dist/build/listlike-tests/listlike-tests-tmp/TestInfrastructure.o )

testsrc/TestInfrastructure.hs:268:10: error:
    • No instance for (Semigroup (MyList a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (MyList a)’
    |
268 | instance Monoid (MyList a) where
    |          ^^^^^^^^^^^^^^^^^
Failed to install ListLike-4.5.1
```

**Comment by konn** [comment]
@asr Thanks, good catch! I've just pushed the changes to make tests compile with GHC 8.4.x.

@JohnLato Is there any plan to merge this pull req?

**Comment by ddssff** [comment]
I believe I can merge it.

**Comment by asr** [comment]
@ddssff, thank you for merging and releasing!

**Comment by konn** [comment]
@ddssff Thanks!
